---
- name: Change guest username
  hosts: all
  
  tasks:
  - name: Remove guest username
    win_user:
    #ansible.windows.win_user:
      name: "{{ guest_username_old }}"
      state: absent
      
  - name: Create guest username with different name
    win_user:
    #ansible.windows.win_user:
      name: "{{ guest_username_new }}"
      state: present
      account_disabled: yes